language: python
python:
- '3.6.1'
- '3.6.2'
- nightly

env:
- BUILD_MODULE=examples/java BUILD_OPTIONS="-d java.dist_type=onejar"
- BUILD_MODULE=examples/java BUILD_OPTIONS="-d java.dist_type=merge"


install:
- pip install git+https://github.com/nodepy/nodepy.git@master
- nodepy --version
- nppm install -I
- export PATH="nodepy_modules/.bin:$PATH"

script:
- "craftr -m ${BUILD_MODULE} $BUILD_OPTIONS build :run"
