language: python
python:
- '3.6.1'
- '3.6.2'
- nightly

# Currently fails because of a bug in typing.NamedTuple. We could
# probably work around it using craftr/lib/types:NamedObject instead.
#- '3.6.0'

matrix:
- fast_finish: true
- allow_failures:
  - python: '3.6.0'

env:
- BUILD_MODULE=examples/java BUILD_OPTIONS="-d java.dist_type=onejar"
- BUILD_MODULE=examples/java BUILD_OPTIONS="-d java.dist_type=merge"
- BUILD_MODULE=examples/csharp

install:
- sudo apt-get update
- pip install git+https://github.com/nodepy/nodepy.git@master
- nodepy --version
- nppm install -I
- export PATH="nodepy_modules/.bin:$PATH"
# Install Mono
- if [[ "$BUILD_MODULE" == "examples/csharp" ]]; then
    sudo apt-get -qq -y install mono-devel gtk-sharp2;
  fi

script:
- "craftr -m ${BUILD_MODULE} $BUILD_OPTIONS build :run"
