language: python
python:
- '3.6.1'
- '3.6.2'
- nightly

install:
- pip install git+https://github.com/nodepy/nodepy.git@master
- nodepy --version
- nppm install -I

script:
# Build the example Java project.
- pushd examples/java
# Build using the onejar option.
- nppm run craftr --build-directory build-onejar/ -d java.dist_type=onejar build
- java -jar build-onejar/scopes/craftr.examples-java/main.jar
# Build using the merge option.
- nppm run craftr --build-directory build-merge/ -d java.dist_type=merge build
- java -jar build-merge/scopes/craftr.examples-java/main.jar
